### ISSUE TITLE
Attributeerror for bool8 to bool in numpy?

### ISSUE THREAD

**Issue by ghxstweb** [CadQuery/cadquery#1626]
![image](https://github.com/user-attachments/assets/1300c7f7-09aa-4198-9bcf-576a76033cc1)

Hi all, with just a basic installation of cadquery, im getting this issue:

raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool8'. Did you mean: 'bool'?

my numpy version is 2.0.0, do I need to downgrade it in order to use cadquery?

**Comment by jmwright** [comment]
See #1616

**Comment by sbalk** [comment]
For now, downgrade numpy to 1.23.5 because from [1.24 it's deprecated](https://numpy.org/doc/stable/release/1.24.0-notes.html#np-str0-and-similar-are-now-deprecated).

**Comment by AnonymouZEE** [comment]
same problem... 
please replace all numpy.bool8 with numpy.bool_ 
...or avoid NumPy types for booleans

**Comment by adam-urbanczyk** [comment]
This is fixed in master, see #1617

**Comment by YahliGilboa** [comment]
still didnt work for me. had to revert to numpy 1.23.5

**Comment by adam-urbanczyk** [comment]
What did not work exactly in master? How did you install it? Which dep gives the error?

**Comment by ulikoehler** [comment]
I can confirm that upgrading to cadquery master fixes this issue for me.

Command I used:

```sh
pip install --user -U git+https://github.com/CadQuery/cadquery.git --break-system-packages
```

with current master revision = [5429f61](https://github.com/CadQuery/cadquery/commit/5429f618c6723b47f07ba5394a912e22b0dd5cff)

**Comment by zakzook333** [comment]
Neither solution worked for me, I always get "Process finished with exit code -1073741819 (0xC0000005)" error" and I don't know why. I tried clean installation from master in virtual environment with latest pip, but I still get this error.

**Comment by ulikoehler** [comment]
@zakzook333 I believe the "Process finished fwith exit code" is a totally different error and I'd guess its opencascade related but not sure. Can you share a full stacktrace?

**Comment by zakzook333** [comment]
I don't have a full stracktrace. I only put "import cadquery" into the script and it gives me this error. The interesting thing is that when I type "import cadquery" followed by "cadquery.Workplane('XY').box(1,2,3).toSvg()" directly into python console I get raw SVG output as I am supposed to get. I tried to run the script from both python console and PyCharm.

**Comment by davidedelvento** [comment]
> AttributeError: 'Editor' object has no attribute 'run_cell_action'

A decent workaround is to run the following. This is assuming you have a dedicated virtual environment for this, if you don't, you are likely to break other things. If you use conda/mamba, I have no idea, since I don't use them

```
pip install nlopt==2.7.1
pip install numpy==1.23.5
pip install spyder==5
```

Explanation:
* the numpy is what is suggested to do by others in this ticket, however that alone is insufficient, because it conflicts with the latest `nlopt` which is otherwise installed, so we need to downgrade that
* such a downgrade is a pain to identify but you can get a list of candidates with `pip index versions nlopt`. Then by trial and error which each version, go into a browser and try every version starting from https://pypi.org/pypi/nlopt/2.9.0/json and search for the numpy dependency. The newest version that does not require numpy 2 is https://pypi.org/pypi/nlopt/2.7.1/json and that is what I selected
* With that solved, we are bitten by https://github.com/CadQuery/CQ-editor/issues/455 and the last line solves that

But yes, it would be nice to have such things included in the `requirements.txt` rather than having to reverse engineering it.

**Comment by jmwright** [comment]
This should be fixed now that CadQuery 2.5.2 is available.
