### ISSUE TITLE
Incorrect cutting with filleted shapes

### ISSUE THREAD

**Issue by billingsley-john** [CadQuery/cadquery#540]
I have been trying to perform a cut between shapes in arranged like the following using cadquery master.

![Screenshot from 2020-12-10 14-01-50](https://user-images.githubusercontent.com/56687624/101782190-9ddcfe00-3af0-11eb-9e6e-dce00708216c.png)

The filleted cuboids are cut from the outer round shape to create 'ports'.

When the cuboids are not filleted, the desired effect is achieved:

![Screenshot from 2020-12-10 14-10-05](https://user-images.githubusercontent.com/56687624/101782886-78042900-3af1-11eb-9172-6de38234b5fa.png)

However, adding fillets to the cuboid edges causes problems. Sometimes cuts are not performed:

![Screenshot from 2020-12-10 14-12-34](https://user-images.githubusercontent.com/56687624/101783137-cb767700-3af1-11eb-8ea7-6fb34b98f431.png)

and sometimes, additionally, outer shape becomes mishapen - it is no longer has a smooth outer surface.

![Screenshot from 2020-12-10 14-03-06](https://user-images.githubusercontent.com/56687624/101783493-42137480-3af2-11eb-8a30-25fa0ff8f3f1.png)
![Screenshot from 2020-12-10 14-03-15](https://user-images.githubusercontent.com/56687624/101783500-43dd3800-3af2-11eb-816f-92ff33c4c283.png)

Does anyone know what might be causing this issue?

**Comment by billingsley-john** [comment]
Apologies for the absence of a MWE. I will try to provide one soon.

**Comment by billingsley-john** [comment]
Also, to note, I have checked that both the rounded outer surface and cutting cuboids are created correctly before the cut takes place in each case shown above (I have just shown the failed resulting cut).

**Comment by adam-urbanczyk** [comment]
Looks like `ShapeUpgrade_UnifySameDomain` issue. Maybe try to cut with `clean=False`?

**Comment by jmwright** [comment]
Those screenshots look like they could have been taken while using FreeCAD. If you're using FreeCAD (CadQuery 1.x). I'd like to confirm whether you're using the newer 2.x version of FreeCAD. The following code works fine for me in the latest CQ-editor binary build.
```
import cadquery as cq

# A very crude approximation of your sphere
core = cq.Workplane("XY").sphere(10, angle3=180).cut(cq.Workplane("XY").sphere(9.8)).center(0, 0).circle(3.0).cutThruAll()

# The cutout object
cutout = cq.Workplane("YZ").rect(3, 3).extrude(13).edges("|X").fillet(0.5).rotateAboutCenter((0, 0, 1), 45)#.transformed(rotate=(0, 0, 45))

result = core.cut(cutout)

show_object(result)
```
![Screenshot from 2020-12-10 19-41-02](https://user-images.githubusercontent.com/1015439/101846766-a698f880-3b1f-11eb-8d42-d9ef155f338f.png)

Interestingly though if I use the "ZX" workplane for the cutout, the fillet is lost.

![Screenshot from 2020-12-10 19-42-06](https://user-images.githubusercontent.com/1015439/101846833-cc260200-3b1f-11eb-846c-47d44b3bc55a.png)

**Comment by jmwright** [comment]
I forgot to try the cut with `clean=False`. It does not fix the issue when using the ZX plane.
```python
import cadquery as cq

# A very crude approximation of your sphere
core = cq.Workplane("XY").sphere(10, angle3=180).cut(cq.Workplane("XY").sphere(9.8)).center(0, 0).circle(3.0).cutThruAll()

# The cutout object
cutout = cq.Workplane("ZX").rect(3, 3).extrude(13).edges("|X").fillet(0.5).rotateAboutCenter((0, 0, 1), 45)#.transformed(rotate=(0, 0, 45))

result = core.cut(cutout, clean=False)

show_object(result)
```

**Comment by adam-urbanczyk** [comment]
This is what I see for ZX:
![image](https://user-images.githubusercontent.com/13981538/101878043-32963900-3b8f-11eb-904a-77100e62902a.png)

**Comment by jmwright** [comment]
Ah, I didn't think about that happening. I'm assuming the ends are filleted because what we see as the green Y axis becomes the `xDir` (0, 1, 0) for the workplane when `ZX` is used.

**Comment by jmwright** [comment]
Oh, and another thing I made a mistake on is rotating the cutout bar about the center. In the original screenshots that bar is rotated so that it's aligned with the center of the sphere. Using `rotate()` instead with the appropriate axis vectors should fix that.

**Comment by jmwright** [comment]
I guess I'm confused about the ZX plane after looking at the docs. https://cadquery.readthedocs.io/en/latest/classreference.html?highlight=plane#cadquery.Plane

**Comment by billingsley-john** [comment]
Hi @adam-urbanczyk and @jmwright , thank you both for your responses. I just wanted to mention a few things that might help solve this issue!

Unfortunately, performing cut with `clean=False` didn't solve the problem, however, the result produced wasn't identical. As pictured below, with clean=False the partial outline of a missing ports became visible.

![Screenshot from 2020-12-11 12-46-41](https://user-images.githubusercontent.com/56687624/101905210-f8d52a80-3bae-11eb-888b-48f0ff5d4a7e.png)

Another thing is that the multiple cutting cuboids are not a set of individual solids - together they are one solid. I don't know whether this changes your outlook on the issue.

Finally, I am only using FreeCAD to view the geometry. I use CadQuery 2 (master branch) to create the solids and export them as stp files, but view them using FreeCAD.

Thanks again, and I will be sure to update this issue with any further developments!

**Comment by adam-urbanczyk** [comment]
@billingsley-john  could you export the two shapes before cutting as breps and share them here? This is the simplest way to repoduce the issue.

**Comment by billingsley-john** [comment]
Hi @adam-urbanczyk, sorry for the delay. I have the breps of the shapes. Do you just want the contents of each file in a comment on this issue? I can't share the file itself.

**Comment by adam-urbanczyk** [comment]
You can zip the brep files and attach in a comment.

**Comment by billingsley-john** [comment]
[geometry.zip](https://github.com/CadQuery/cadquery/files/5714618/geometry.zip)

**Comment by adam-urbanczyk** [comment]
@billingsley-john I tried different cut settings using OCCT directly, but did not manage to get any improvement.

Assuming that your spherical object is made using `parametricCurve` could you check if #694 has any effect?

**Comment by billingsley-john** [comment]
Thank you for the response @adam-urbanczyk. Unfortunately, #694 did not fix this specific problem - construction errors were still observed when cuts were made with filleted shapes. The cutting shape is created by filleting the edges of cadquery solid, which is created by extruding a polyline connecting points together.
